version: '2'

services:
  app:
    build:
      context: .
    command: /bin/bash -c "go run *.go"
    volumes:
        - ./:/app
    ports:
        - '8080:8080'

  prometheus:
    image: prom/prometheus:0.18.0
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus_data:/prometheus
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'

  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
        - ./grafana_data:/var/lib/grafana